### PR TITLE
Update setup.js in attempt to get colour borders to work

### PR DESCRIPTION
**Pull request by daniep01**
I think the colour choices need to start with a capital letter to work. This is not what it says in the manual but I have had success getting it to work this way.

### CODE REVIEW

**Comment by krocheck** [comment]
We'll need to do an upgrade script for this because it is a breaking change.

**Comment by daniep01** [comment]
Is that something I can assist with?

**Comment by daniep01** [comment]
Can this be progressed to enable a merge? I think a few people would like to see the borders working, especially useful for tally.

**Comment by sausix** [comment]
> I think the colour choices need to start with a capital letter to work. This is not what it says in the manual but I have had success getting it to work this way.

It's not related to the communication protocol.

By testing with netcat I can confirm, capital and non capital colors work both.

Problem is that color definition get's translated to `undefined`.

`Border: undefined`

I will test the fix when I'm back on site.

**Comment by krocheck** [comment]
ohhh ... I see it.  I can fix tonight probably.

**Pull request closed without merging**
